version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:12
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword


